version: '3.8'

services:
  web:
    build: .
    container_name: static-site
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-site.rule=Host(`localhost`)"
      - "traefik.http.services.static-site.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a simple monitoring service
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    restart: unless-stopped
    networks:
      - web-network
    profiles:
      - monitoring

networks:
  web-network:
    driver: bridge

# Alternative configuration for using pre-built image from Docker Hub
# Uncomment the section below and comment out the 'build: .' line above
# if you're using a pre-built image from Docker Hub
#
# services:
#   web:
#     image: your-dockerhub-username/static-site:latest
#     container_name: static-site
#     ports:
#       - "80:80"
#     restart: unless-stopped
